SB__version_DBCategories = "2.2.0"

DBCategories = {};

DBCategories["MANGER"] = {"sb_manger", "sb_poulette", "sb_faireamanger", "sb_gras", "sb_grasvie", "sb_jambon", "sb_marine", "sb_porcelet", "sb_chips", "sb_collation", "sb_faim", "sb_mangeralcool", "sb_muffin", "sb_potatoes", "sb_protein", "sb_everydayimdrinking", "sb_takoyaki", "sb_americanramen", "sb_calamari", "sb_knackis", "sb_muffinfactory", "sb_omelette", "sb_toomanycooks", "sb_warmbeer", "sb_yourdinner"};
DBCategories["STRAT"] = {"sb_ahcca", "sb_capital", "sb_carrer", "sb_couilles_short", "sb_debile", "sb_demarre", "sb_ecoute", "sb_explique", "sb_faux", "sb_fleches", "sb_foutre", "sb_heure", "sb_intro", "sb_poney", "sb_raison", "sb_rallonge", "sb_secouer", "sb_toutafe", "sb_communiquer", "sb_coquille", "sb_crucial", "sb_détails", "sb_facile", "sb_marre", "sb_notes", "sb_respect", "sb_riencompris", "sb_calmezvous", "sb_cobble", "sb_raclée", "sb_chuispasrassuré", "sb_heylisten", "sb_jenecomprendspas", "sb_firepit", "sb_maydie"};
DBCategories["PULL"] = {"sb_engarde", "sb_formotherrussia", "sb_letsgo", "sb_gobwah", "sb_engarde2", "sb_mecreant", "sb_mecreant2", "sb_kickass", "sb_leeroy", "sb_baseball", "sb_cparti", "sb_fairedumal", "sb_fairemerde", "sb_jevaisvoir", "sb_killedmyfather", "sb_marmotte", "sb_ninja", "sb_petitebite", "sb_poing", "sb_souffrance", "sb_tazer", "sb_zob", "sb_calmezvous", "sb_muda", "sb_chargez", "sb_elan", "sb_minus", "sb_extralargecanofwhoopass", "sb_imafirinmahlazor", "sb_lightyouup", "sb_quandvousvoulez", "sb_cestatoi", "sb_holydagger", "sb_maydie", "sb_notsafe", "sb_pieds", "sb_playtimeisover"};
DBCategories["COUNTDOWN"] = {"sb_54321"};
DBCategories["AGGRO"] = {"sb_assassin", "sb_moi", "sb_aggro"};
DBCategories["DEATH"] = {"sb_nul", "sb_passera", "sb_badumkss", "sb_boulette", "sb_fatality", "sb_gameover", "sb_heknew", "sb_fairedelamerde", "sb_motus", "sb_shame", "sb_wasted", "sb_wiii", "sb_Wilhelm", "sb_chiale", "sb_deux", "sb_douleur", "sb_déteste", "sb_marteau", "sb_oublier", "sb_tropvite", "sb_viol", "sb_youdied", "sb_zut", "sb_whenyoutryyourbest", "sb_pain", "sb_painlong", "sb_reinflate", "sb_therethere", "sb_amoungus", "sb_desballes", "sb_disapointed", "sb_glue", "sb_justtosuffer", "sb_medic", "sb_neck", "sb_notmad", "sb_ohnoanyway", "sb_aaahcomeon", "sb_lookatthis", "sb_dumbwaystodie", "sb_fuckthisshit", "sb_squack", "sb_aspirine", "sb_betonniere", "sb_fleshwound", "sb_cestconca", "sb_hahailmabieneu", "sb_hopital", "sb_matinal"};
DBCategories["WYPE"] = {"sb_directedby", "sb_ok", "sb_whenyoutryyourbest", "sb_chier", "sb_connard", "sb_cul", "sb_etcdelamerde", "sb_fulgurant", "sb_honteux", "sb_merde", "sb_sable", "sb_vacherie", "sb_nein", "sb_nogodpleaseno", "sb_nooooo", "sb_wtfboom", "sb_catastrophe", "sb_ccaca", "sb_cestnul", "sb_commencebien", "sb_deadpeople", "sb_degueulasse", "sb_delamerde", "sb_flop", "sb_pifpaf", "sb_piquotte", "sb_punition", "sb_raclette", "sb_raining", "sb_sadpiano", "sb_unjob", "sb_baston", "sb_deshonneur", "sb_groove", "sb_holyshit1", "sb_holyshit2", "sb_nigerundayo", "sb_notepic", "sb_notepicslow", "sb_coda", "sb_coffin", "sb_disapointed", "sb_escalated", "sb_justtosuffer", "sb_maman", "sb_notmad", "sb_sonofabitch", "sb_venividivici", "sb_criticalmissionfailure", "sb_dumbwaystodie", "sb_eric_andre_transition", "sb_fuckitall", "sb_fuckthisshit", "sb_muller", "sb_nulachier", "sb_powerdown", "sb_squack", "sb_we_clearly_dont_get_it", "sb_cestconca", "sb_chiantos", "sb_gameoverVS", "sb_hahailmabieneu", "sb_hopital", "sb_ilestfort", "sb_lattage", "sb_matinal", "sb_run"};
DBCategories["DOWN"] = {"sb_bien", "sb_chier_bout", "sb_fache", "sb_mortel", "sb_poil", "sb_pro", "sb_quequette", "sb_slibard", "sb_victoire", "sb_julien", "sb_ohyeah", "sb_yeah", "sb_yes", "sb_badass", "sb_bravo", "sb_impressionnant", "sb_merciderien", "sb_prendsca", "sb_baston", "sb_davyepic", "sb_iapprove", "sb_goodnews", "sb_hinjaku", "sb_iapprove", "sb_legalydead", "sb_nopower", "sb_nice", "sb_respect+", "sb_supereasy", "sb_monster_kill", "sb_lattage", "sb_jetaieu", "sb_noice", "sb_reallycool"};
DBCategories["LOOT"] = {"sb_pigeon", "sb_item", "sb_mine", "sb_brilliant", "sb_respect+", "sb_diablo_legendary_drop", "sb_itssofluffy", "sb_pppplease", "sb_noice", "sb_vscoffre1", "sb_vscoffre3", "sb_vscoffre5"};
DBCategories["REZ"] = {"sb_angels", "sb_hichealhcare", "sb_healthcare", "sb_therethere", "sb_desballes", "sb_glue", "sb_medic", "sb_medicine", "sb_onrecuperelesrescape", "sb_tespasmouru", "sb_getupbitc", "sb_pasmort"};

DBCategories["LAVA"] = {"sb_lava"};
DBCategories["NOT LAVA"] = {"sb_notlava"};

DBCategories["NON"] = {"sb_non", "sb_narp", "sb_nonono"};
DBCategories["SAD"] = {"sb_whenyoutryyourbest", "sb_myself", "sb_sad", "sb_silence", "sb_violon", "sb_sorry", "sb_youarefine", "sb_sadschindler", "sb_naruto"};
DBCategories["SILENCE"] = {"sb_casuffit", "sb_discuter", "sb_esbaudir", "sb_fermer", "sb_fermetagueule", "sb_galere", "sb_jenaimarre", "sb_rienacarrer1", "sb_taisez", "sb_ikillyou", "sb_toitagueule", "sb_vent", "sb_arreterparler", "sb_fermezla", "sb_shutup", "sb_tagueule", "sb_tagueuuuule", "sb_sitdown"};
DBCategories["ATTENTE"] = {"sb_bite", "sb_demi", "sb_elevator", "sb_jeopardy", "sb_crickets", "sb_technicalerror", "sb_ronfle", "sb_whatareyouwaitingfor"};
DBCategories["BONJOUR"] = {"sb_cons", "sb_glandu", "sb_bonsoir", "sb_canard", "sb_hellomine", "sb_hellosing", "sb_bonjour", "sb_gentlemen", "sb_hellomotherfucker", "sb_goodmorningvietnam", "sb_tuturu", "sb_whatsupslapers", "sb_whats_up_fuckers", "sb_coucou", "sb_herewegoagain", "sb_hi", "sb_itsyou", "sb_mylord1", "sb_mylord2", "sb_mylord3", "sb_salutbandede"};
DBCategories["BONJOUR AD"] = {"sb_AD_salut01", "sb_AD_salut02", "sb_AD_salut03", "sb_AD_salut04", "sb_AD_salut05", "sb_AD_salut07", "sb_AD_salut08", "sb_AD_salut09", "sb_AD_salut10", "sb_AD_salut11", "sb_AD_salut12", "sb_AD_salut13", "sb_AD_salut14", "sb_AD_salut15", "sb_AD_salut16", "sb_AD_salut17", "sb_AD_salut18", "sb_AD_salut19", "sb_AD_salut21", "sb_AD_salut22", "sb_AD_salut23", "sb_AD_salut24", "sb_AD_salut26", "sb_AD_salut27", "sb_AD_salut28", "sb_AD_salut30", "sb_AD_salut31", "sb_AD_salut32", "sb_AD_salut33", "sb_AD_salut34", "sb_AD_salut35", "sb_AD_salut36", "sb_AD_salut37"};
DBCategories["AU REVOIR"] = {"sb_aurevoir", "sb_abientot", "sb_goodafternoon", "sb_tendresseetchocolat", "sb_yippeekiyay"};
DBCategories["DECO"] = {"sb_internet"};

DBCategories["MUSIC"] = {"sb_bennyhill", "sb_canttouchthis", "sb_champions", "sb_Lalalala", "sb_petitponey", "sb_rickroll", "sb_star", "sb_trololo", "sb_truant", "sb_acdc", "sb_americano", "sb_canardcoincoin", "sb_cena", "sb_cykablyat", "sb_derp", "sb_dropthebass", "sb_epic", "sb_firstsight", "sb_fox", "sb_fox_bad", "sb_goodenough", "sb_guile", "sb_initialD", "sb_love", "sb_nyan", "sb_oursbrun", "sb_sax", "sb_selfie", "sb_sexy", "sb_striptease", "sb_tatata", "sb_tralala", "sb_valkyries", "sb_aaaaah", "sb_aerobic", "sb_bird", "sb_caravan", "sb_formotherrussia", "sb_letsgo", "sb_poireau", "sb_tristitude", "sb_spooky", "sb_wearen1", "sb_holyshit1", "sb_holyshit2", "sb_coda", "sb_coffin", "sb_dejavu2", "sb_flydragon1", "sb_flydragon2", "sb_oakvale", "sb_shuffling", "sb_superperforator", "sb_absolutehardbass", "sb_allstars", "sb_battlestar", "sb_boots", "sb_countryroads", "sb_cubanpete", "sb_dovahkiin", "sb_dumbwaystodie", "sb_everydayimdrinking", "sb_fallout3", "sb_fuckitall", "sb_humsoung", "sb_klaxon", "sb_metallicaathome", "sb_moneyfornothing", "sb_noot", "sb_pacificrim", "sb_pulpfiction", "sb_putinbutt", "sb_resisteprouvequetuexistes", "sb_shoop", "sb_stayingalive", "sb_supertimor", "sb_tunaktunaktun", "sb_whatislove", "sb_x_files", "sb_ballsoffire", "sb_bennyhillslow", "sb_biddiBobbidiBoo", "sb_cheeki_breeki", "sb_chikiban", "sb_diablo_rushed", "sb_edgerunner", "sb_el_Sonidito", "sb_erikaaa", "sb_flute", "sb_futurama", "sb_gali", "sb_goodenough_long", "sb_jump", "sb_knockeddown", "sb_megalovania", "sb_moneymoney", "sb_move_bitch", "sb_negociation", "sb_nomorefucks", "sb_nowork", "sb_popipo", "sb_ppap", "sb_seth", "sb_shiny", "sb_swing", "sb_thatthingyoudo", "sb_thisisshit", "sb_trooper", "sb_venus", "sb_Yoru_ni_Kakeru"};
DBCategories["LOL"] = {"sb_aaaaah", "sb_galles", "sb_ambiance", "sb_banned", "sb_doyouknowtheway", "sb_razowski", "sb_jingle", "sb_leeroy", "sb_murloc", "sb_princesse", "sb_shindeiru", "sb_sitcom", "sb_souffrir", "sb_stopit", "sb_gueuse", "sb_connerie", "sb_agrapheuse", "sb_ah", "sb_alerte", "sb_chemise", "sb_colifichet", "sb_considerer", "sb_dramatic", "sb_eddymalou", "sb_enigme 2", "sb_enigme", "sb_leviosa", "sb_nature", "sb_ngengen", "sb_piege", "sb_porte", "sb_poulette", "sb_racaille", "sb_viens", "sb_rage", "sb_refuse", "sb_suspense", "sb_uhwtf", "sb_whatthecut", "sb_yooo", "sb_directedby", "sb_gobwah", "sb_blague", "sb_diablo", "sb_fishing", "sb_geranium", "sb_jeanne", "sb_raf", "sb_roulettes", "sb_suponjubobu", "sb_woop", "sb_bourne", "sb_razowski", "sb_cobble", "sb_fbi", "sb_fenneko", "sb_maman", "sb_surprise", "sb_utini", "sb_baguevalide", "sb_balalalala", "sb_damn_boi", "sb_horns", "sb_koyaanisqatsi", "sb_lautreilfaitsesbruits", "sb_lookatthis", "sb_onlyagame", "sb_papaya", "sb_ph", "sb_pokemon", "sb_pppplease", "sb_abandonne", "sb_arialaugh", "sb_ayayay", "sb_bonchasseur", "sb_codeavecquoi", "sb_croissant", "sb_dindon", "sb_discordjoined", "sb_discordleave", "sb_discordnotif", "sb_emotionnaldamage", "sb_gostavoalmadovar", "sb_groupir", "sb_hehe", "sb_hhhh", "sb_idgas", "sb_joker_haha", "sb_KEKW", "sb_lambertlaugh", "sb_magic", "sb_meuporg", "sb_peupeupeu", "sb_pingouin", "sb_poison", "sb_potato", "sb_puteapoits", "sb_saloooope", "sb_sncf", "sb_spaghet", "sb_stupidbitch", "sb_tadaaa", "sb_thatswhatshesaid", "sb_theyesneedtheno", "sb_toctoc", "sb_tp", "sb_uwu", "sb_whatdoido", "sb_wow", "sb_yamete", "sb_yamete2", "sb_yamete3"};
DBCategories["NEW"] = {"sb_abandonne", "sb_aggro", "sb_americanramen", "sb_arialaugh", "sb_aspirine", "sb_ayayay", "sb_ballsoffire", "sb_bennyhillslow", "sb_betonniere", "sb_biddiBobbidiBoo", "sb_bonchasseur", "sb_calamari", "sb_cestatoi", "sb_cestconca", "sb_cheeki_breeki", "sb_chiantos", "sb_chikiban", "sb_codeavecquoi", "sb_coucou", "sb_croissant", "sb_diablo_rushed", "sb_dindon", "sb_discordjoined", "sb_discordleave", "sb_discordnotif", "sb_edgerunner", "sb_el_Sonidito", "sb_emotionnaldamage", "sb_erikaaa", "sb_firepit", "sb_fleshwound", "sb_flute", "sb_futurama", "sb_gali", "sb_gameoverVS", "sb_getupbitc", "sb_goodenough_long", "sb_gostavoalmadovar", "sb_groupir", "sb_hahailmabieneu", "sb_hehe", "sb_herewegoagain", "sb_hhhh", "sb_hi", "sb_holydagger", "sb_hopital", "sb_idgas", "sb_ilestfort", "sb_itsyou", "sb_jetaieu", "sb_joker_haha", "sb_jump", "sb_KEKW", "sb_knackis", "sb_knockeddown", "sb_lambertlaugh", "sb_lattage", "sb_magic", "sb_matinal", "sb_maydie", "sb_megalovania", "sb_meuporg", "sb_moneymoney", "sb_move_bitch", "sb_muffinfactory", "sb_mylord1", "sb_mylord2", "sb_mylord3", "sb_narp", "sb_naruto", "sb_negociation", "sb_noice", "sb_nomorefucks", "sb_nonono", "sb_notsafe", "sb_nowork", "sb_omelette", "sb_pasmort", "sb_peupeupeu", "sb_pieds", "sb_pingouin", "sb_playtimeisover", "sb_poison", "sb_popipo", "sb_potato", "sb_ppap", "sb_puteapoits", "sb_reallycool", "sb_ronfle", "sb_run", "sb_saloooope", "sb_salutbandede", "sb_seth", "sb_shiny", "sb_sitdown", "sb_sncf", "sb_spaghet", "sb_stupidbitch", "sb_swing", "sb_tadaaa", "sb_thatswhatshesaid", "sb_thatthingyoudo", "sb_theyesneedtheno", "sb_thisisshit", "sb_toctoc", "sb_toomanycooks", "sb_tp", "sb_trooper", "sb_uwu", "sb_venus", "sb_vscoffre1", "sb_vscoffre3", "sb_vscoffre5", "sb_warmbeer", "sb_whatareyouwaitingfor", "sb_whatdoido", "sb_wow", "sb_yamete", "sb_yamete2", "sb_yamete3", "sb_Yoru_ni_Kakeru", "sb_yourdinner"};

DBWednesday = {};
DBWednesday["WED"] = {"sb_wed1", "sb_wed10", "sb_wed11", "sb_wed12", "sb_wed13", "sb_wed14", "sb_wed15", "sb_wed16", "sb_wed2", "sb_wed3", "sb_wed4", "sb_wed5", "sb_wed6", "sb_wed7", "sb_wed8", "sb_wed9"}